name: Update Sitemap Dates

on:
  schedule:
    - cron: '0 6 * * 1'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual run

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update lastmod dates in sitemap.xml
        run: |
          TODAY=$(date -u +"%Y-%m-%d")
          sed -i "s|<lastmod>[^<]*</lastmod>|<lastmod>${TODAY}</lastmod>|g" sitemap.xml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sitemap.xml
          git commit -m "Auto-update sitemap lastmod to ${TODAY}" || echo "No changes to commit"
          git push
